# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9aeb6ef5428e97955484ad5153d7dcc0432ec6bdf2b870e8ffd3c96267a817adb3e111c49a4d15fe784210251b617a4995371a457f484e29c28e8fc1b08b1115

test:
  secret_key_base: cce83908fb7a7fe36c33f0e943c5e2b71e1e61f5dc32653a681f8eb2c2a7da02c0651711f2ea1b570684b8dc2822b07b54e5fe8f8ff6912bccd59369f184c6ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
